### PR TITLE
added composer file

### PR DESCRIPTION
**Pull request by domdambrogia**

### CODE REVIEW

**Comment by airesvsg** [comment]
Hi @domdambrogia,
Thanks for you PR, but I think it is not necessary.
Thanks again

**Comment by oppodeldoc** [comment]
@airesvsg Thanks so much for this great plugin. Having a composer.json file would be helpful for those of us that wish to manage our WP Plugins via Composer. Is there a reason why you wouldn't want to support that?

Also, I noticed there's a lot of help wanted tags on the closed issues. Are you looking for contributors? We're looking to use your plugin on a couple projects and I'd be happy to help with some PRs and maintenance if we can.

**Comment by samrap** [comment]
I think this is extremely necessary. Composer is the official package manager for the entire PHP ecosystem. Not adhering to this standard is considered bad practice by many. While WordPress plugins are typically managed within the back end of WordPress or using the WP CLI, there is a large community using [Bedrock](https://github.com/roots/bedrock) to build their WordPress sites, as it provides developers with modern tooling and standards. The recommended way to install plugins using Bedrock is via Composer. All plugins registered officially through WordPress are available via Composer thanks to [WordPress Packagist](https://wpackagist.org/). Not supporting installation via Composer is blatantly lacking support for the large community of Bedrock developers and all other WordPress developers using Composer.

Thank you for your awesome work on this plugin, but I really do not see the argument against Composer support. Composer is about as "official" as it gets for package management in PHP. Perhaps you have a better explanation of why you are rejecting this PR.

**Comment by airesvsg** [comment]
@samrap I understood your point of view, I'm opening the PR.
@domdambrogia Please, make the changes below in your `composer.js`. 
You need to change the version and fill the author informations.
```JSON
{
  "name": "airesvsg/acf-to-rest-api",
  "description": "Exposes Advanced Custom Fields Endpoints in the WordPress REST API",
  "type": "wordpress-plugin",
  "version": "3.0.0-beta",
  "keywords": ["wordpress", "wp", "rest-api", "acf", "wp-api", "json", "wordpres-plugin", "fields"],
  "homepage": "https://github.com/airesvsg/acf-to-rest-api",
  "license": "GPLv2.0+",
  "authors": [
    {
      "name": "Aires Gonçalves",
      "email": "airesvsg@gmail.com",
      "homepage": "http://airesgoncalves.com",
      "role": "Developer"
    }
  ],
  "support": {
    "email": "airesvsg@gmail.com",
    "issues": "https://github.com/airesvsg/acf-to-rest-api/issues"
  },
  "require": {
    "php": ">=5.3.2",
    "composer/installers": "~1.0"
  }
}
```
Thanks

**Comment by samrap** [comment]
Thanks for reconsidering!

**Comment by domdambrogia** [comment]
Awesome plugin, I've used it on multiple projects. Thanks for reconsidering the PR, I've updated the `composer.json` file as requested. As a composer user it makes my development process much more fluid. Thanks!

**Pull request merged**
